### ISSUE TITLE
【BUG】out of memory when running vgg16

### ISSUE THREAD

**Issue by qzylalala** [illinois-impact/puma-compiler#6]
When I ran VGG16, I got:
```
Partitioning graph... done.
Physical layout... done.
Memory allocation... done.
MVM coalescing... [1]    51630 killed     ./vgg16.test
```
"top" command showed that memory not enough.
However, I have 256G memory. Any suggestions?

Thanks

**Comment by ielhajj** [comment]
MVM coalescing is very memory hungry. Try disabling it for large models.

**Comment by qzylalala** [comment]
> MVM coalescing is very memory hungry. Try disabling it for large models.

Thanks.  I set `coalesceMVMOperations_` to false,  and recompiled.
However, I get another error when running vgg16:
```
Partitioning graph... done.
Physical layout... done.
Memory allocation... done.
Linearizing graph... done.
Register allocation... [1]    58211 segmentation fault (core dumped)  ./vgg16.test
```

**Comment by ielhajj** [comment]
Register allocation can also use up too much memory for large models.

The src Makefile by default uses -O0 -g. Try using -O3 instead. This will optimize time and memory consumption.

If that still doesn't work, one workaround is to compile and simulate each layer separately. This will reduce the size of the compiled graph. It would also allow you to simulate the layers in parallel for faster simulation time.
